apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: terraria-server
  labels:
    app: terraria-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraria-server
  template:
    metadata:
      labels:
        app: terraria-server
    spec:
      containers:
        - image: asia.gcr.io/euphoric-quanta-171208/terraria
          name: terraria-server
          tty: true
          stdin: true
          ports:
            - containerPort: 7777
              name: terraria-server
          volumeMounts:
            - name: terraria-server-persistent-storage
              mountPath: /world
      volumes:
        - name: terraria-server-persistent-storage
          gcePersistentDisk:
            pdName: terraria-server-disk
            fsType: ext4