apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: terraria-server
  labels:
    app: terraria-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraria-server
  template:
    metadata:
      labels:
        app: terraria-server
    spec:
      containers:
        - image: asia.gcr.io/graphic-parsec-262612/terraria:1404
          name: terraria-server
          tty: true
          stdin: true
          ports:
            - containerPort: 7777
              name: terraria-server
          volumeMounts:
            - name: terraria-server-persistent-storage
              mountPath: /config
          env:
            - name: world
              value: "Journey_End.wld"
          # args: ["-world", "/config/Journey_End.wld"] 
      volumes:
        - name: terraria-server-persistent-storage
          gcePersistentDisk:
            pdName: terraria-server-disk
            fsType: ext4