apiVersion: v1
kind: Service
metadata:
  labels:
    app: terraria-server
  name: terraria-server
spec:
  type: LoadBalancer
  type: NodePort
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
  selector:
    app: terraria-server
  # loadBalancerIP: "35.247.183.210"