apiVersion: v1
kind: Service
metadata:
  labels:
    app: tmodloader
  name: tmodloader
spec:
  # type: LoadBalancer
  type: NodePort
  ports:
    - port: 7777
      targetPort: 7777
      nodePort: 30777
      protocol: TCP
  selector:
    app: tmodloader
  # loadBalancerIP: "35.247.183.210"